[FJD-200] Create an Accordion block
fivejars/booster_drupal pull request #100
Opened 2024-09-27 11:29 UTC by MamoruFivejars

2024-09-30 08:20 UTC, OleksandrRiumshyn requested changes

2024-09-30 08:20 UTC, OleksandrRiumshyn commented on recipes/accordion_block_type/config/core.entity_form_display.block_content.accordion.default.yml
> +  langcode:
Could be removed

2024-09-30 08:20 UTC, OleksandrRiumshyn commented on recipes/accordion_block_type/config/core.entity_form_display.block_content.accordion_item.default.yml
> +  langcode:
Could be removed

2024-09-30 11:02 UTC, MamoruFivejars commented on recipes/accordion_block_type/config/core.entity_form_display.block_content.accordion.default.yml
> +  langcode:
Done

2024-09-30 11:02 UTC, MamoruFivejars commented on recipes/accordion_block_type/config/core.entity_form_display.block_content.accordion_item.default.yml
> +  langcode:
Done

2024-10-01 10:40 UTC, OleksandrRiumshyn requested changes

2024-10-01 10:40 UTC, OleksandrRiumshyn commented on recipes/accordion_block_type/config/field.field.block_content.accordion_item.body.yml
> +  allowed_formats: {  }
Only basic_html and plain text formats should be allowed

2024-10-02 07:28 UTC, MamoruFivejars commented on recipes/accordion_block_type/config/field.field.block_content.accordion_item.body.yml
> +  allowed_formats: {  }
Done

2024-10-02 08:23 UTC, OleksandrRiumshyn approved these changes

2024-10-02 08:23 UTC, merged