[DO NOT MERGE] [FJD-216] Demo
fivejars/booster_drupal pull request #112
Opened 2024-10-24 14:06 UTC by david-storm

Demo for https://fivejars.atlassian.net/browse/FJD-216

2024-10-29 10:11 UTC, OleksandrRiumshyn requested changes

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on Jenkinsfile
> +    DB_DATA_VOLUME = ""
Should be in separate commit and separate branch with separate PR. Here is an example https://github.com/fivejars/booster_drupal/pull/111
https://github.com/fivejars/booster_drupal/pull/110

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/alerts/recipe.yml
> +  import:
What about other installed module configurations? Would be better to add direct rules

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/alerts/recipe.yml
> +      - node.type.alert.yml
There is no such a config in module node

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/alerts/recipe.yml
> +      - taxonomy.vocabulary.alert_severity.yml
There is no such a config in module taxonomy

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/alerts/recipe.yml
> +      - views.view.alerts.yml
There is no such a config in module views

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/booster/recipe.yml
> +  - events
This is the wrong naming for the recipes. Check please page content type recipe as example

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/events/recipe.yml
> +    core.entity_form_display.node.event.default:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/events/recipe.yml
> +      createIfNotExists:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/events/recipe.yml
> +      createIfNotExists:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/location/recipe.yml
> +      createIfNotExists:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/location/recipe.yml
> +      createIfNotExists:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/location/recipe.yml
> +      createIfNotExists:
Looks like it could be done by config

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/person/config/field.storage.node.field_person_image.yml
> +langcode: en
Why do not use media?

2024-10-29 10:11 UTC, OleksandrRiumshyn commented on recipes/person/recipe.yml
> +      createIfNotExists:
Should be done as config

2024-10-29 14:16 UTC, david-storm commented on recipes/alerts/recipe.yml
> +      - node.type.alert.yml
fix

2024-10-29 14:55 UTC, david-storm commented on recipes/alerts/recipe.yml
> +      - views.view.alerts.yml
fixed

2024-10-29 15:24 UTC, david-storm commented on recipes/location/recipe.yml
> +      createIfNotExists:
added

2024-10-29 15:25 UTC, david-storm commented on recipes/location/recipe.yml
> +      createIfNotExists:
fixed

2024-10-29 15:25 UTC, david-storm commented on recipes/location/recipe.yml
> +      createIfNotExists:
fixed

2024-10-29 15:25 UTC, david-storm commented on recipes/person/config/field.storage.node.field_person_image.yml
> +langcode: en
changed

2024-10-29 15:25 UTC, david-storm commented on recipes/person/recipe.yml
> +      createIfNotExists:
fixed

2024-10-30 12:44 UTC, OleksandrRiumshyn commented on recipes/alert_content_type/recipe.yml
> +type: 'Site'
Use please "type: 'Content type'"

2024-10-30 12:45 UTC, OleksandrRiumshyn commented on recipes/event_content_type/recipe.yml
> +    pathauto: "*"
What about other installed module configurations? Would be better to add direct rules, use ~ to skip config import for some modules. 
for example:
node: ~

2024-10-30 12:45 UTC, OleksandrRiumshyn commented on recipes/location_content_type/recipe.yml
> +type: recipe
Use please "type: 'Content type'"

2024-10-30 12:45 UTC, OleksandrRiumshyn commented on recipes/person_content_type/recipe.yml
> +type: module
Use please "type: 'Content type'"

2024-10-30 12:46 UTC, OleksandrRiumshyn commented on recipes/location_content_type/config/core.entity_form_display.node.location.default.yml
> +uuid: b7c21dc3-4b47-4965-8cb0-dfabd6ac1493
The "uuid" property should be removed

2024-10-30 12:46 UTC, OleksandrRiumshyn commented on recipes/person_content_type/config/field.storage.node.field_person_image.yml
> +uuid: d1ae8952-9579-4293-a4c8-a97868dd23a5
The "uuid" property should be removed

2024-11-15 10:15 UTC, closed without merging