[FJD-163] Add Card Grid block recipe
fivejars/booster_drupal pull request #88
Opened 2024-09-16 06:42 UTC by MamoruFivejars

2024-09-16 11:05 UTC, OleksandrRiumshyn requested changes

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/config/language.content_settings.block_content.card.yml
> +langcode: en
Looks like this config could be skipped

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/config/language.content_settings.block_content.grid_content.yml
> +langcode: en
Looks like this config could be skipped

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/config/image.style.card_1x.yml
> +label: 'Card (1x)'
Would be better to specify that it related with some default behavior

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/config/responsive_image.styles.card_grid.yml
> +label: 'Card Grid'
Would be better to specify that it related with some default behavior

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/recipe.yml
> +    user.role.contributor:
Role can be missing, it requires some other recipes dependencies (see other recipes)

2024-09-16 11:05 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/recipe.yml
> +  - focal_point
Focal point not related to this recipe

2024-09-16 11:21 UTC, OleksandrRiumshyn requested changes

2024-09-16 11:21 UTC, OleksandrRiumshyn commented on recipes/card_grid_block_type/config/responsive_image.styles.card_grid_2c.yml
> +id: card_grid_2c
Not so good style naming “2c” is not clear for understanding

2024-09-17 10:13 UTC, MamoruFivejars commented on recipes/card_grid_block_type/recipe.yml
> +    user.role.contributor:
This is now irrelevant in the latest recipes

2024-09-17 12:56 UTC, OleksandrRiumshyn approved these changes

2024-09-17 12:56 UTC, OleksandrRiumshyn commented on recipes/grid_content_block_type/config/core.entity_form_display.block_content.card.default.yml
> +  langcode:
As usual we don't add this dependency to recipes because it use default value

2024-09-17 12:56 UTC, OleksandrRiumshyn commented on recipes/grid_content_block_type/config/core.entity_form_display.block_content.grid_content.default.yml
> +    type: language_select
As usual we don't add this dependency to recipes because it use default value

2024-09-17 12:56 UTC, OleksandrRiumshyn commented on recipes/grid_content_block_type/config/core.entity_view_display.block_content.card.2_columns.yml
> +  search_api_excerpt: true
Search API module can not exists

2024-09-17 12:56 UTC, OleksandrRiumshyn commented on recipes/grid_content_block_type/config/core.entity_view_display.block_content.card.3_columns.yml
> +  search_api_excerpt: true
Search API module can not exist

2024-09-17 12:56 UTC, OleksandrRiumshyn commented on recipes/grid_content_block_type/config/core.entity_view_display.block_content.grid_content.default.yml
> +  search_api_excerpt: true
Search API module can not exist

2024-09-23 11:04 UTC, merged